services:
  inspector:
    build:
      context: .
    environment:
      NODE_ENV: production
      VUE_APP_SOLO_URL: http://localhost:8669
    volumes:
      - "./public/abis:/usr/share/nginx/html/abis"
    ports:
      - 8083:80
